import type { FilterAsset, FilterCategory } from "./types";

export const LOCAL_FILTER_CATEGORIES: FilterCategory[] = [
  { id: "essentials", name: "Essentials", description: "Essentials filters" },
  { id: "portrait", name: "Portrait", description: "Portrait filters" },
  { id: "landscape", name: "Landscape", description: "Landscape filters" },
  { id: "cinematic", name: "Cinematic", description: "Cinematic filters" },
  { id: "movies", name: "Movies", description: "Movie-style filters" },
  { id: "vintage", name: "Vintage", description: "Vintage filters" },
  { id: "vibrant", name: "Vibrant", description: "Vibrant filters" },
  { id: "mono", name: "Mono", description: "Monochrome filters" },
  { id: "aesthetic", name: "Aesthetic", description: "Aesthetic filters" },
  { id: "life", name: "Life", description: "Everyday life filters" },
];

export const LOCAL_FILTERS: FilterAsset[] = [
  { id: "filter-vivid", name: "Vivid", type: "filter", category: "essentials", description: "Boost saturation and contrast", thumbnail: "", gradingParams: { saturation: 0.3, contrast: 0.2 } },
  { id: "filter-cool", name: "Cool", type: "filter", category: "essentials", description: "Cool blue tone", thumbnail: "", gradingParams: { temperature: -0.2, saturation: -0.1 } },
  { id: "filter-warm", name: "Warm", type: "filter", category: "essentials", description: "Warm golden tone", thumbnail: "", gradingParams: { temperature: 0.2, saturation: 0.1 } },
  { id: "filter-cinematic-teal", name: "Cinematic Teal", type: "filter", category: "cinematic", description: "Teal-orange cinematic grade", thumbnail: "", gradingParams: { temperature: -0.1, tint: -0.1, contrast: 0.15, saturation: 0.1 } },
  { id: "filter-purple-haze", name: "Purple Haze", type: "filter", category: "cinematic", description: "Purple tint with contrast", thumbnail: "", gradingParams: { temperature: 0.1, tint: 0.2, saturation: 0.1, contrast: 0.15 } },
  { id: "filter-vintage", name: "Vintage", type: "filter", category: "vintage", description: "Faded sepia vintage", thumbnail: "", gradingParams: { sepia: 0.4, contrast: 0.1, brightness: -0.05, saturation: -0.1 } },
  { id: "filter-bw-classic", name: "B&W Classic", type: "filter", category: "mono", description: "Classic black and white", thumbnail: "", gradingParams: { grayscale: 1, contrast: 0.2 } },
  { id: "filter-high-contrast", name: "High Contrast", type: "filter", category: "mono", description: "Strong black and white", thumbnail: "", gradingParams: { grayscale: 1, contrast: 0.5, brightness: -0.1 } },
  { id: "filter-soft-bw", name: "Soft B&W", type: "filter", category: "mono", description: "Gentle monochrome", thumbnail: "", gradingParams: { grayscale: 1, contrast: -0.1, brightness: 0.05 } },
  { id: "filter-bleach", name: "Bleach Bypass", type: "filter", category: "cinematic", description: "Desaturated high contrast", thumbnail: "", gradingParams: { saturation: -0.3, contrast: 0.3, brightness: -0.05 } },
  { id: "filter-golden-hour", name: "Golden Hour", type: "filter", category: "portrait", description: "Warm sunny glow", thumbnail: "", gradingParams: { temperature: 0.3, saturation: 0.2, brightness: 0.05, contrast: 0.1 } },
  { id: "filter-ocean-blue", name: "Ocean Blue", type: "filter", category: "landscape", description: "Cool ocean tones", thumbnail: "", gradingParams: { temperature: -0.3, saturation: 0.15, brightness: 0.05 } },
  { id: "filter-rose-gold", name: "Rose Gold", type: "filter", category: "aesthetic", description: "Warm rosy tint", thumbnail: "", gradingParams: { tint: 0.2, temperature: 0.1, saturation: 0.1, contrast: 0.1 } },
  { id: "filter-forest", name: "Forest", type: "filter", category: "landscape", description: "Deep green tones", thumbnail: "", gradingParams: { temperature: -0.1, tint: -0.1, saturation: 0.2, contrast: 0.1 } },
  { id: "filter-sunset-glow", name: "Sunset Glow", type: "filter", category: "vibrant", description: "Warm sunset with pink", thumbnail: "", gradingParams: { temperature: 0.2, tint: 0.2, saturation: 0.2, brightness: 0.05, contrast: 0.1 } },
  { id: "filter-cold-night", name: "Cold Night", type: "filter", category: "cinematic", description: "Cold blue night scene", thumbnail: "", gradingParams: { temperature: -0.4, saturation: -0.1, brightness: -0.05, contrast: 0.1 } },
  { id: "filter-morning-light", name: "Morning Light", type: "filter", category: "life", description: "Soft bright morning", thumbnail: "", gradingParams: { brightness: 0.15, temperature: 0.1, saturation: 0.1, contrast: -0.05 } },
  { id: "filter-moody-film", name: "Moody Film", type: "filter", category: "movies", description: "Dark moody film look", thumbnail: "", gradingParams: { contrast: 0.2, brightness: -0.1, saturation: -0.1, vignette: 0.3 } },
  { id: "filter-retro-80s", name: "Retro 80s", type: "filter", category: "vintage", description: "Bright 80s retro", thumbnail: "", gradingParams: { saturation: 0.3, contrast: 0.2, sepia: 0.2, tint: 0.1 } },
  { id: "filter-clean-white", name: "Clean White", type: "filter", category: "aesthetic", description: "Clean bright minimal", thumbnail: "", gradingParams: { brightness: 0.15, contrast: 0.1, saturation: -0.1 } },
  { id: "filter-deep-contrast", name: "Deep Contrast", type: "filter", category: "movies", description: "Heavy contrast dramatic", thumbnail: "", gradingParams: { contrast: 0.6, brightness: -0.15, saturation: -0.1 } },
  { id: "filter-soft-pastel", name: "Soft Pastel", type: "filter", category: "aesthetic", description: "Pastel soft colors", thumbnail: "", gradingParams: { saturation: 0.2, brightness: 0.1, contrast: -0.1 } },
  { id: "filter-urban-steel", name: "Urban Steel", type: "filter", category: "landscape", description: "Cool urban metal", thumbnail: "", gradingParams: { contrast: 0.3, saturation: -0.2, temperature: -0.1 } },
  { id: "filter-autumn-leaves", name: "Autumn Leaves", type: "filter", category: "landscape", description: "Warm autumn tones", thumbnail: "", gradingParams: { temperature: 0.2, sepia: 0.2, saturation: 0.2, contrast: 0.1 } },
  { id: "filter-winter-frost", name: "Winter Frost", type: "filter", category: "landscape", description: "Cool bright winter", thumbnail: "", gradingParams: { temperature: -0.3, brightness: 0.1, saturation: -0.1 } },
  { id: "filter-neon-city", name: "Neon City", type: "filter", category: "vibrant", description: "Neon saturated look", thumbnail: "", gradingParams: { saturation: 0.4, contrast: 0.3, tint: 0.2 } },
  { id: "filter-silk", name: "Silk", type: "filter", category: "portrait", description: "Smooth soft skin", thumbnail: "", gradingParams: { brightness: 0.1, contrast: -0.1, saturation: -0.1 } },
  { id: "filter-honey", name: "Honey", type: "filter", category: "portrait", description: "Warm honey glow", thumbnail: "", gradingParams: { temperature: 0.25, saturation: 0.2, brightness: 0.05, contrast: 0.05 } },
  { id: "filter-ice", name: "Ice", type: "filter", category: "essentials", description: "Icy cold blue", thumbnail: "", gradingParams: { temperature: -0.4, saturation: -0.2, brightness: 0.05 } },
  { id: "filter-warm-ember", name: "Warm Ember", type: "filter", category: "life", description: "Warm cozy ember", thumbnail: "", gradingParams: { temperature: 0.35, saturation: 0.15, brightness: -0.05, contrast: 0.1 } },
  { id: "filter-cool-breeze", name: "Cool Breeze", type: "filter", category: "life", description: "Fresh cool air", thumbnail: "", gradingParams: { temperature: -0.25, saturation: 0.1, brightness: 0.05 } },
  { id: "filter-vintage-fade", name: "Vintage Fade", type: "filter", category: "vintage", description: "Faded vintage photo", thumbnail: "", gradingParams: { sepia: 0.3, contrast: -0.1, brightness: 0.05, saturation: -0.1 } },
  { id: "filter-matte", name: "Matte", type: "filter", category: "movies", description: "Matte film finish", thumbnail: "", gradingParams: { contrast: 0.1, brightness: -0.05, saturation: -0.1, vignette: 0.2 } },
  { id: "filter-bright-pop", name: "Bright Pop", type: "filter", category: "vibrant", description: "Bright vivid pop", thumbnail: "", gradingParams: { saturation: 0.5, brightness: 0.1, contrast: 0.2 } },
  { id: "filter-cream", name: "Cream", type: "filter", category: "aesthetic", description: "Soft creamy warm", thumbnail: "", gradingParams: { temperature: 0.15, brightness: 0.1, saturation: -0.1 } },
  { id: "filter-charcoal", name: "Charcoal", type: "filter", category: "mono", description: "Dark charcoal mono", thumbnail: "", gradingParams: { grayscale: 1, contrast: 0.4, brightness: -0.05 } },
  { id: "filter-silver", name: "Silver", type: "filter", category: "mono", description: "Bright silver mono", thumbnail: "", gradingParams: { grayscale: 1, brightness: 0.1, contrast: 0.2 } },
  { id: "filter-amber", name: "Amber", type: "filter", category: "portrait", description: "Warm amber tone", thumbnail: "", gradingParams: { temperature: 0.3, saturation: 0.2, brightness: 0.05, contrast: 0.05 } },
  { id: "filter-teal-pop", name: "Teal Pop", type: "filter", category: "vibrant", description: "Teal and orange pop", thumbnail: "", gradingParams: { temperature: -0.2, saturation: 0.3, contrast: 0.2 } },
  { id: "filter-noir", name: "Noir", type: "filter", category: "movies", description: "Classic film noir", thumbnail: "", gradingParams: { grayscale: 1, contrast: 0.5, brightness: -0.15, vignette: 0.3 } },
  { id: "filter-sepia-dream", name: "Sepia Dream", type: "filter", category: "vintage", description: "Strong sepia dream", thumbnail: "", gradingParams: { sepia: 0.6, contrast: 0.1, brightness: -0.05 } },
  { id: "filter-kodak-gold", name: "Kodak Gold", type: "filter", category: "vintage", description: "Kodak Gold film", thumbnail: "", gradingParams: { temperature: 0.25, sepia: 0.2, saturation: 0.2, contrast: 0.15 } },
  { id: "filter-fuji-film", name: "Fuji Film", type: "filter", category: "movies", description: "Fuji film color", thumbnail: "", gradingParams: { saturation: 0.3, contrast: 0.2, temperature: -0.1 } },
  { id: "filter-agfa", name: "Agfa", type: "filter", category: "vintage", description: "Agfa film look", thumbnail: "", gradingParams: { contrast: 0.3, saturation: -0.2, brightness: -0.05 } },
  { id: "filter-polaroid", name: "Polaroid", type: "filter", category: "vintage", description: "Instant Polaroid", thumbnail: "", gradingParams: { brightness: 0.15, saturation: -0.1, contrast: -0.1, vignette: 0.1 } },
  { id: "filter-lomo", name: "Lomo", type: "filter", category: "vibrant", description: "Lomography style", thumbnail: "", gradingParams: { saturation: 0.4, contrast: 0.3, vignette: 0.3 } },
  { id: "filter-velvet", name: "Velvet", type: "filter", category: "portrait", description: "Soft velvet portrait", thumbnail: "", gradingParams: { contrast: 0.2, brightness: -0.05, saturation: -0.1 } },
  { id: "filter-pearl", name: "Pearl", type: "filter", category: "aesthetic", description: "Pearl soft glow", thumbnail: "", gradingParams: { brightness: 0.15, saturation: -0.2, contrast: 0.1 } },
  { id: "filter-bronze", name: "Bronze", type: "filter", category: "portrait", description: "Warm bronze skin", thumbnail: "", gradingParams: { temperature: 0.3, sepia: 0.3, contrast: 0.2 } },
  { id: "filter-arctic", name: "Arctic", type: "filter", category: "landscape", description: "Frozen arctic blue", thumbnail: "", gradingParams: { temperature: -0.5, saturation: -0.1, brightness: 0.1 } },
  { id: "filter-neon", name: "Neon", type: "filter", category: "vibrant", description: "Intense neon colors", thumbnail: "", gradingParams: {"saturation":0.6,"contrast":0.4,"tint":0.3} },
  { id: "filter-pastel", name: "Pastel", type: "filter", category: "aesthetic", description: "Soft pastel tones", thumbnail: "", gradingParams: {"saturation":0.15,"brightness":0.1,"contrast":-0.1} },
  { id: "filter-noir-2", name: "Film Noir", type: "filter", category: "movies", description: "High contrast noir", thumbnail: "", gradingParams: {"grayscale":1,"contrast":0.7,"brightness":-0.2,"vignette":0.4} },
  { id: "filter-sunrise", name: "Sunrise", type: "filter", category: "portrait", description: "Warm golden sunrise", thumbnail: "", gradingParams: {"temperature":0.4,"saturation":0.3,"brightness":0.1} },
  { id: "filter-ocean", name: "Deep Ocean", type: "filter", category: "landscape", description: "Deep blue cinematic", thumbnail: "", gradingParams: {"temperature":-0.4,"saturation":0.2,"contrast":0.2} },
  { id: "filter-autumn", name: "Autumn", type: "filter", category: "vintage", description: "Warm autumn colors", thumbnail: "", gradingParams: {"temperature":0.3,"sepia":0.3,"saturation":0.2} },
  { id: "filter-forest-2", name: "Forest Green", type: "filter", category: "landscape", description: "Rich green forest", thumbnail: "", gradingParams: {"temperature":-0.2,"tint":-0.2,"saturation":0.3} },
  { id: "filter-candy", name: "Candy", type: "filter", category: "vibrant", description: "Bright candy colors", thumbnail: "", gradingParams: {"saturation":0.7,"contrast":0.1,"brightness":0.05,"tint":0.2} },
  { id: "filter-mono-blue", name: "Mono Blue", type: "filter", category: "mono", description: "Blue-tinted monochrome", thumbnail: "", gradingParams: {"grayscale":1,"temperature":-0.3,"contrast":0.3} },
  { id: "filter-dusk", name: "Dusk", type: "filter", category: "cinematic", description: "Purple dusk tones", thumbnail: "", gradingParams: {"temperature":0.1,"tint":0.3,"saturation":0.2,"contrast":0.2} },
  { id: "filter-sepia-warm", name: "Sepia Warm", type: "filter", category: "vintage", description: "Warm sepia tone", thumbnail: "", gradingParams: {"sepia":0.5,"temperature":0.2,"contrast":0.1} },
  { id: "filter-cool-silver", name: "Cool Silver", type: "filter", category: "cinematic", description: "Cool metallic silver", thumbnail: "", gradingParams: {"temperature":-0.3,"contrast":0.3,"saturation":-0.2} },
  { id: "filter-forest-dark", name: "Forest Dark", type: "filter", category: "landscape", description: "Dark forest greens", thumbnail: "", gradingParams: {"temperature":-0.1,"tint":-0.2,"saturation":0.3,"contrast":0.2,"brightness":-0.1} },
  { id: "filter-sunset-pink", name: "Sunset Pink", type: "filter", category: "portrait", description: "Warm pink sunset", thumbnail: "", gradingParams: {"temperature":0.3,"tint":0.4,"saturation":0.2,"brightness":0.05} },
  { id: "filter-mono-soft", name: "Mono Soft", type: "filter", category: "mono", description: "Soft grey monochrome", thumbnail: "", gradingParams: {"grayscale":1,"contrast":-0.1,"brightness":0.08} },
  { id: "filter-vintage-fade-2", name: "Vintage Fade 2", type: "filter", category: "vintage", description: "Extra faded vintage", thumbnail: "", gradingParams: {"sepia":0.4,"contrast":-0.2,"brightness":0.1,"saturation":-0.2} },
  { id: "filter-neon-blue", name: "Neon Blue", type: "filter", category: "vibrant", description: "Intense neon blue", thumbnail: "", gradingParams: {"saturation":0.6,"contrast":0.4,"temperature":-0.4,"tint":0.1} },
  { id: "filter-golden", name: "Golden", type: "filter", category: "cinematic", description: "Golden cinematic", thumbnail: "", gradingParams: {"temperature":0.4,"saturation":0.3,"contrast":0.2,"brightness":0.05} },
  { id: "filter-urban", name: "Urban", type: "filter", category: "landscape", description: "Urban grey tones", thumbnail: "", gradingParams: {"contrast":0.4,"saturation":-0.3,"temperature":-0.1} },
  { id: "filter-pastel-blue", name: "Pastel Blue", type: "filter", category: "aesthetic", description: "Soft pastel blue", thumbnail: "", gradingParams: {"saturation":-0.1,"brightness":0.1,"temperature":-0.2,"contrast":-0.1} },
  { id: "filter-mono-dark", name: "Mono Dark", type: "filter", category: "mono", description: "Dark high-contrast mono", thumbnail: "", gradingParams: {"grayscale":1,"contrast":0.5,"brightness":-0.1} },
  { id: "filter-vivid-warm", name: "Vivid Warm", type: "filter", category: "vibrant", description: "Vivid warm colors", thumbnail: "", gradingParams: {"saturation":0.5,"temperature":0.3,"contrast":0.2} },
  { id: "filter-cool-fade", name: "Cool Fade", type: "filter", category: "cinematic", description: "Cool faded film", thumbnail: "", gradingParams: {"temperature":-0.3,"saturation":-0.2,"contrast":-0.1,"brightness":0.08} },
  { id: "filter-autumn-orange", name: "Autumn Orange", type: "filter", category: "vintage", description: "Warm orange autumn", thumbnail: "", gradingParams: {"temperature":0.4,"sepia":0.3,"saturation":0.3} },
  { id: "filter-forest-fresh", name: "Forest Fresh", type: "filter", category: "landscape", description: "Fresh green forest", thumbnail: "", gradingParams: {"temperature":-0.2,"tint":-0.3,"saturation":0.4,"brightness":0.05} },
  { id: "filter-sunset-purple", name: "Sunset Purple", type: "filter", category: "portrait", description: "Purple sunset glow", thumbnail: "", gradingParams: {"temperature":0.1,"tint":0.4,"saturation":0.2,"contrast":0.1} },
  { id: "filter-mono-blue-2", name: "Mono Blue 2", type: "filter", category: "mono", description: "Deep blue monochrome", thumbnail: "", gradingParams: {"grayscale":1,"temperature":-0.4,"contrast":0.3,"brightness":-0.05} },
  { id: "filter-neon-pink", name: "Neon Pink", type: "filter", category: "vibrant", description: "Intense neon pink", thumbnail: "", gradingParams: {"saturation":0.6,"contrast":0.4,"tint":0.5} },
  { id: "filter-golden-hour-2", name: "Golden Hour 2", type: "filter", category: "portrait", description: "Extra warm golden hour", thumbnail: "", gradingParams: {"temperature":0.5,"saturation":0.25,"brightness":0.1,"contrast":0.1} },
  { id: "filter-cinematic-dark", name: "Cinematic Dark", type: "filter", category: "cinematic", description: "Dark moody cinematic", thumbnail: "", gradingParams: {"contrast":0.4,"brightness":-0.15,"saturation":-0.1,"vignette":0.3} },
  { id: "filter-rose", name: "Rose", type: "filter", category: "aesthetic", description: "Soft rose tint", thumbnail: "", gradingParams: {"tint":0.3,"saturation":0.15,"brightness":0.05} },
  { id: "filter-ocean-fade", name: "Ocean Fade", type: "filter", category: "cinematic", description: "Faded ocean blue", thumbnail: "", gradingParams: {"temperature":-0.4,"saturation":-0.1,"contrast":-0.1,"brightness":0.05} },
  { id: "filter-sunset-warm", name: "Sunset Warm", type: "filter", category: "portrait", description: "Extra warm sunset", thumbnail: "", gradingParams: {"temperature":0.5,"saturation":0.3,"brightness":0.05} },
  { id: "filter-mono-blue-3", name: "Mono Blue 3", type: "filter", category: "mono", description: "Cool blue mono", thumbnail: "", gradingParams: {"grayscale":1,"temperature":-0.5,"contrast":0.25} },
  { id: "filter-neon-green-2", name: "Neon Green 2", type: "filter", category: "vibrant", description: "Vibrant neon green", thumbnail: "", gradingParams: {"saturation":0.6,"contrast":0.4,"tint":-0.4} },
  { id: "filter-golden-hour-3", name: "Golden Hour 3", type: "filter", category: "portrait", description: "Rich golden hour", thumbnail: "", gradingParams: {"temperature":0.6,"saturation":0.3,"brightness":0.08,"contrast":0.1} },
  { id: "filter-pastel-pink-2", name: "Pastel Pink 2", type: "filter", category: "aesthetic", description: "Gentle pastel pink", thumbnail: "", gradingParams: {"tint":0.2,"saturation":0.1,"brightness":0.1} },
  { id: "filter-forest-dark-2", name: "Forest Dark 2", type: "filter", category: "landscape", description: "Deep dark forest", thumbnail: "", gradingParams: {"temperature":-0.2,"tint":-0.3,"saturation":0.25,"brightness":-0.1} },
  { id: "filter-noir-3", name: "Noir 3", type: "filter", category: "movies", description: "Deep noir contrast", thumbnail: "", gradingParams: {"grayscale":1,"contrast":0.7,"brightness":-0.2} },
  { id: "filter-vintage-soft", name: "Vintage Soft", type: "filter", category: "vintage", description: "Soft vintage fade", thumbnail: "", gradingParams: {"sepia":0.35,"contrast":-0.15,"brightness":0.08} },
];