// Local built-in text effect presets for immediate availability.
// These are merged into the effects store at startup, so users see them
// without needing API access.

export const localTextEffectPresets: any[] = [
  {
    id: "local-lemon-burst",
    name: "Lemon Burst",
    description: "Bright yellow pop with a soft glow",
    font: {
      family: "Poppins",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffe066" }],
    strokes: [{ color: "#b38600", width: 2 }],
    shadows: [{ color: "#ffe066", blur: 16, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ffe066", radius: 18, intensity: 0.6 }],
  },
  {
    id: "local-milk-soft",
    name: "Milk Soft",
    description: "Gentle white with subtle shadow",
    font: {
      family: "Nunito",
      weight: 700,
      style: "normal",
      letterSpacing: 0.5,
      lineHeight: 1.2,
    },
    fills: [{ color: "#f8fafc" }],
    strokes: [{ color: "#cbd5e1", width: 1 }],
    shadows: [{ color: "#94a3b8", blur: 8, offsetX: 1, offsetY: 2 }],
  },
  {
    id: "local-ink-brush",
    name: "Ink Brush",
    description: "Bold black ink with rough edges",
    font: {
      family: "Permanent Marker",
      weight: 400,
      style: "normal",
      letterSpacing: 1,
      lineHeight: 1.1,
    },
    fills: [{ color: "#1a1a1a" }],
    strokes: [{ color: "#0f0f0f", width: 4 }],
  },
  {
    id: "local-neon-pulse",
    name: "Neon Pulse",
    description: "Electric blue-pink neon glow",
    font: {
      family: "Bangers",
      weight: 400,
      style: "normal",
      letterSpacing: 2,
      lineHeight: 1.1,
    },
    fills: [{ color: "#00f0ff" }],
    strokes: [{ color: "#ff2d55", width: 2 }],
    shadows: [{ color: "#00f0ff", blur: 20, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ff2d55", radius: 24, intensity: 0.7 }],
  },
  {
    id: "local-glitch",
    name: "Glitch",
    description: "Digital distortion red/cyan",
    font: {
      family: "Press Start 2P",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    strokes: [{ color: "#ff2d55", width: 2 }],
    shadows: [{ color: "#00f0ff", blur: 4, offsetX: -2, offsetY: 0 }],
    glows: [{ color: "#ff2d55", radius: 10, intensity: 0.6 }],
  },
  {
    id: "local-gold-shine",
    name: "Gold Shine",
    description: "Luxury metallic gold",
    font: {
      family: "Playfair Display",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffe066, #b38600" }],
    strokes: [{ color: "#8a6d1a", width: 2 }],
    shadows: [{ color: "#ffe066", blur: 12, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ffcc00", radius: 16, intensity: 0.5 }],
  },
];
