// Local built-in text effect presets for immediate availability.
// These are merged into the effects store at startup, so users see them
// without needing API access.

export const localTextEffectPresets: any[] = [
  {
    id: "local-lemon-burst",
    name: "Lemon Burst",
    description: "Bright yellow pop with a soft glow",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-lemon-burst.png",
    font: {
      family: "Poppins",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffe066" }],
    strokes: [{ color: "#b38600", width: 2 }],
    shadows: [{ color: "#ffe066", blur: 16, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ffe066", radius: 18, intensity: 0.6 }],
  },
  {
    id: "local-milk-soft",
    name: "Milk Soft",
    description: "Gentle white with subtle shadow",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-milk-soft.png",
    font: {
      family: "Nunito",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#f8fafc" }],
    strokes: [{ color: "#cbd5e1", width: 1 }],
    shadows: [{ color: "#94a3b8", blur: 8, offsetX: 1, offsetY: 2 }],
  },
  {
    id: "local-ink-brush",
    name: "Ink Brush",
    description: "Bold black ink with rough edges",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-ink-brush.png",
    font: {
      family: "Permanent Marker",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1a1a1a" }],
    strokes: [{ color: "#0f0f0f", width: 4 }],
  },
  {
    id: "local-neon-pulse",
    name: "Neon Pulse",
    description: "Electric blue-pink neon glow",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-neon-pulse.png",
    font: {
      family: "Bangers",
      weight: 400,
      style: "normal",
      letterSpacing: 2,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00f0ff" }],
    strokes: [{ color: "#ff2d55", width: 2 }],
    shadows: [{ color: "#00f0ff", blur: 20, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ff2d55", radius: 24, intensity: 0.7 }],
  },
  {
    id: "local-glitch",
    name: "Glitch",
    description: "Digital distortion red/cyan",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-glitch.png",
    font: {
      family: "Press Start 2P",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    strokes: [{ color: "#ff2d55", width: 2 }],
    shadows: [{ color: "#00f0ff", blur: 4, offsetX: -2, offsetY: 0 }],
    glows: [{ color: "#ff2d55", radius: 10, intensity: 0.6 }],
  },
  {
    id: "local-gold-shine",
    name: "Gold Shine",
    description: "Luxury metallic gold",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-gold-shine.png",
    font: {
      family: "Playfair Display",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffe066, #b38600" }],
    strokes: [{ color: "#8a6d1a", width: 2 }],
    shadows: [{ color: "#ffe066", blur: 12, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ffcc00", radius: 16, intensity: 0.5 }],
  },
  {
    id: "local-effect-1",
    name: "Soft Glow",
    description: "Local text effect number 1",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-1.png",
    font: {
      family: "Poppins",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-2",
    name: "Neon Pop",
    description: "Local text effect number 2",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-2.png",
    font: {
      family: "Roboto Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-3",
    name: "Golden Touch",
    description: "Local text effect number 3",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-3.png",
    font: {
      family: "Montserrat Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffa502" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-4",
    name: "Ice Chrome",
    description: "Local text effect number 4",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-4.png",
    font: {
      family: "Space Grotesk Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffdd59" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-5",
    name: "Pastel Dream",
    description: "Local text effect number 5",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-5.png",
    font: {
      family: "Outfit Variable",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#2ed573" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-6",
    name: "Retro Vibes",
    description: "Local text effect number 6",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-6.png",
    font: {
      family: "Oswald",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1e90ff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-7",
    name: "Comic Pop",
    description: "Local text effect number 7",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-7.png",
    font: {
      family: "Raleway",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#a55eea" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-8",
    name: "Urban Edge",
    description: "Local text effect number 8",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-8.png",
    font: {
      family: "Playfair Display",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9ff3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-9",
    name: "Bubble Gum",
    description: "Local text effect number 9",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-9.png",
    font: {
      family: "Anton",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00d2d3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-10",
    name: "Silk Screen",
    description: "Local text effect number 10",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-10.png",
    font: {
      family: "Bebas Neue",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#feca57" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-11",
    name: "Royal Blue",
    description: "Local text effect number 11",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-11.png",
    font: {
      family: "Dancing Script",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#48dbfb" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-12",
    name: "Mint Fresh",
    description: "Local text effect number 12",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-12.png",
    font: {
      family: "Pacifico",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9f43" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-13",
    name: "Sunset Fade",
    description: "Local text effect number 13",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-13.png",
    font: {
      family: "Nunito",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#10ac84" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-14",
    name: "Electric Pulse",
    description: "Local text effect number 14",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-14.png",
    font: {
      family: "Inter Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-15",
    name: "Candy Coated",
    description: "Local text effect number 15",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-15.png",
    font: {
      family: "Poppins",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-16",
    name: "Velvet Night",
    description: "Local text effect number 16",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-16.png",
    font: {
      family: "Roboto Variable",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-17",
    name: "Crystal Clear",
    description: "Local text effect number 17",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-17.png",
    font: {
      family: "Montserrat Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffa502" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-18",
    name: "Lime Light",
    description: "Local text effect number 18",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-18.png",
    font: {
      family: "Space Grotesk Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffdd59" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-19",
    name: "Cherry Bomb",
    description: "Local text effect number 19",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-19.png",
    font: {
      family: "Outfit Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#2ed573" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-20",
    name: "Ocean Breeze",
    description: "Local text effect number 20",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-20.png",
    font: {
      family: "Oswald",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1e90ff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-21",
    name: "Amber Glow",
    description: "Local text effect number 21",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-21.png",
    font: {
      family: "Raleway",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#a55eea" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-22",
    name: "Lavender Haze",
    description: "Local text effect number 22",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-22.png",
    font: {
      family: "Playfair Display",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9ff3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-23",
    name: "Cocoa Shine",
    description: "Local text effect number 23",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-23.png",
    font: {
      family: "Anton",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00d2d3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-24",
    name: "Mango Tango",
    description: "Local text effect number 24",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-24.png",
    font: {
      family: "Bebas Neue",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#feca57" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-25",
    name: "Berry Sweet",
    description: "Local text effect number 25",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-25.png",
    font: {
      family: "Dancing Script",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#48dbfb" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-26",
    name: "Pine Fresh",
    description: "Local text effect number 26",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-26.png",
    font: {
      family: "Pacifico",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9f43" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-27",
    name: "Rose Petal",
    description: "Local text effect number 27",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-27.png",
    font: {
      family: "Nunito",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#10ac84" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-28",
    name: "Silver Lining",
    description: "Local text effect number 28",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-28.png",
    font: {
      family: "Inter Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-29",
    name: "Peach Sorbet",
    description: "Local text effect number 29",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-29.png",
    font: {
      family: "Poppins",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-30",
    name: "Midnight Blue",
    description: "Local text effect number 30",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-30.png",
    font: {
      family: "Roboto Variable",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-31",
    name: "Vanilla Cream",
    description: "Local text effect number 31",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-31.png",
    font: {
      family: "Montserrat Variable",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffa502" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-32",
    name: "Crimson Flame",
    description: "Local text effect number 32",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-32.png",
    font: {
      family: "Space Grotesk Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffdd59" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-33",
    name: "Forest Whisper",
    description: "Local text effect number 33",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-33.png",
    font: {
      family: "Outfit Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#2ed573" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-34",
    name: "Sky High",
    description: "Local text effect number 34",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-34.png",
    font: {
      family: "Oswald",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1e90ff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-35",
    name: "Lemon Zest",
    description: "Local text effect number 35",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-35.png",
    font: {
      family: "Raleway",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#a55eea" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-36",
    name: "Coral Reef",
    description: "Local text effect number 36",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-36.png",
    font: {
      family: "Playfair Display",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9ff3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-37",
    name: "Plum Perfect",
    description: "Local text effect number 37",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-37.png",
    font: {
      family: "Anton",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00d2d3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-38",
    name: "Cocoa Butter",
    description: "Local text effect number 38",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-38.png",
    font: {
      family: "Bebas Neue",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#feca57" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-39",
    name: "Ivory Tower",
    description: "Local text effect number 39",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-39.png",
    font: {
      family: "Dancing Script",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#48dbfb" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-40",
    name: "Aqua Fresh",
    description: "Local text effect number 40",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-40.png",
    font: {
      family: "Pacifico",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9f43" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-41",
    name: "Magenta Pop",
    description: "Local text effect number 41",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-41.png",
    font: {
      family: "Nunito",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#10ac84" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-42",
    name: "Honey Drizzle",
    description: "Local text effect number 42",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-42.png",
    font: {
      family: "Inter Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-43",
    name: "Tangerine Dream",
    description: "Local text effect number 43",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-43.png",
    font: {
      family: "Poppins",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-44",
    name: "Mocha Swirl",
    description: "Local text effect number 44",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/thumbnails/text-effects/local-effect-44.png",
    font: {
      family: "Roboto Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
];
