// Local built-in text effect presets for immediate availability.
// These are merged into the effects store at startup, so users see them
// without needing API access.

export const localTextEffectPresets: any[] = [
  {
    id: "local-lemon-burst",
    name: "Lemon Burst",
    description: "Bright yellow pop with a soft glow",
    font: {
      family: "Poppins",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffe066" }],
    strokes: [{ color: "#b38600", width: 2 }],
    shadows: [{ color: "#ffe066", blur: 16, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ffe066", radius: 18, intensity: 0.6 }],
  },
  {
    id: "local-milk-soft",
    name: "Milk Soft",
    description: "Gentle white with subtle shadow",
    font: {
      family: "Nunito",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#f8fafc" }],
    strokes: [{ color: "#cbd5e1", width: 1 }],
    shadows: [{ color: "#94a3b8", blur: 8, offsetX: 1, offsetY: 2 }],
  },
  {
    id: "local-ink-brush",
    name: "Ink Brush",
    description: "Bold black ink with rough edges",
    font: {
      family: "Permanent Marker",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1a1a1a" }],
    strokes: [{ color: "#0f0f0f", width: 4 }],
  },
  {
    id: "local-neon-pulse",
    name: "Neon Pulse",
    description: "Electric blue-pink neon glow",
    font: {
      family: "Bangers",
      weight: 400,
      style: "normal",
      letterSpacing: 2,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00f0ff" }],
    strokes: [{ color: "#ff2d55", width: 2 }],
    shadows: [{ color: "#00f0ff", blur: 20, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ff2d55", radius: 24, intensity: 0.7 }],
  },
  {
    id: "local-glitch",
    name: "Glitch",
    description: "Digital distortion red/cyan",
    font: {
      family: "Press Start 2P",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    strokes: [{ color: "#ff2d55", width: 2 }],
    shadows: [{ color: "#00f0ff", blur: 4, offsetX: -2, offsetY: 0 }],
    glows: [{ color: "#ff2d55", radius: 10, intensity: 0.6 }],
  },
  {
    id: "local-gold-shine",
    name: "Gold Shine",
    description: "Luxury metallic gold",
    font: {
      family: "Playfair Display",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffe066, #b38600" }],
    strokes: [{ color: "#8a6d1a", width: 2 }],
    shadows: [{ color: "#ffe066", blur: 12, offsetX: 0, offsetY: 0 }],
    glows: [{ color: "#ffcc00", radius: 16, intensity: 0.5 }],
  },
  {
    id: "local-effect-1",
    name: "Effect 1",
    description: "Local text effect number 1",
    font: {
      family: "Poppins",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-2",
    name: "Effect 2",
    description: "Local text effect number 2",
    font: {
      family: "Roboto Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-3",
    name: "Effect 3",
    description: "Local text effect number 3",
    font: {
      family: "Montserrat Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffa502" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-4",
    name: "Effect 4",
    description: "Local text effect number 4",
    font: {
      family: "Space Grotesk Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffdd59" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-5",
    name: "Effect 5",
    description: "Local text effect number 5",
    font: {
      family: "Outfit Variable",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#2ed573" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-6",
    name: "Effect 6",
    description: "Local text effect number 6",
    font: {
      family: "Oswald",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1e90ff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-7",
    name: "Effect 7",
    description: "Local text effect number 7",
    font: {
      family: "Raleway",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#a55eea" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-8",
    name: "Effect 8",
    description: "Local text effect number 8",
    font: {
      family: "Playfair Display",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9ff3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-9",
    name: "Effect 9",
    description: "Local text effect number 9",
    font: {
      family: "Anton",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00d2d3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-10",
    name: "Effect 10",
    description: "Local text effect number 10",
    font: {
      family: "Bebas Neue",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#feca57" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-11",
    name: "Effect 11",
    description: "Local text effect number 11",
    font: {
      family: "Dancing Script",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#48dbfb" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-12",
    name: "Effect 12",
    description: "Local text effect number 12",
    font: {
      family: "Pacifico",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9f43" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-13",
    name: "Effect 13",
    description: "Local text effect number 13",
    font: {
      family: "Nunito",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#10ac84" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-14",
    name: "Effect 14",
    description: "Local text effect number 14",
    font: {
      family: "Inter Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-15",
    name: "Effect 15",
    description: "Local text effect number 15",
    font: {
      family: "Poppins",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-16",
    name: "Effect 16",
    description: "Local text effect number 16",
    font: {
      family: "Roboto Variable",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-17",
    name: "Effect 17",
    description: "Local text effect number 17",
    font: {
      family: "Montserrat Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffa502" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-18",
    name: "Effect 18",
    description: "Local text effect number 18",
    font: {
      family: "Space Grotesk Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffdd59" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-19",
    name: "Effect 19",
    description: "Local text effect number 19",
    font: {
      family: "Outfit Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#2ed573" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-20",
    name: "Effect 20",
    description: "Local text effect number 20",
    font: {
      family: "Oswald",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1e90ff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-21",
    name: "Effect 21",
    description: "Local text effect number 21",
    font: {
      family: "Raleway",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#a55eea" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-22",
    name: "Effect 22",
    description: "Local text effect number 22",
    font: {
      family: "Playfair Display",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9ff3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-23",
    name: "Effect 23",
    description: "Local text effect number 23",
    font: {
      family: "Anton",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00d2d3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-24",
    name: "Effect 24",
    description: "Local text effect number 24",
    font: {
      family: "Bebas Neue",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#feca57" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-25",
    name: "Effect 25",
    description: "Local text effect number 25",
    font: {
      family: "Dancing Script",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#48dbfb" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-26",
    name: "Effect 26",
    description: "Local text effect number 26",
    font: {
      family: "Pacifico",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9f43" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-27",
    name: "Effect 27",
    description: "Local text effect number 27",
    font: {
      family: "Nunito",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#10ac84" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-28",
    name: "Effect 28",
    description: "Local text effect number 28",
    font: {
      family: "Inter Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-29",
    name: "Effect 29",
    description: "Local text effect number 29",
    font: {
      family: "Poppins",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-30",
    name: "Effect 30",
    description: "Local text effect number 30",
    font: {
      family: "Roboto Variable",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-31",
    name: "Effect 31",
    description: "Local text effect number 31",
    font: {
      family: "Montserrat Variable",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffa502" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-32",
    name: "Effect 32",
    description: "Local text effect number 32",
    font: {
      family: "Space Grotesk Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffdd59" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-33",
    name: "Effect 33",
    description: "Local text effect number 33",
    font: {
      family: "Outfit Variable",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#2ed573" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-34",
    name: "Effect 34",
    description: "Local text effect number 34",
    font: {
      family: "Oswald",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#1e90ff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-35",
    name: "Effect 35",
    description: "Local text effect number 35",
    font: {
      family: "Raleway",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#a55eea" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-36",
    name: "Effect 36",
    description: "Local text effect number 36",
    font: {
      family: "Playfair Display",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9ff3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-37",
    name: "Effect 37",
    description: "Local text effect number 37",
    font: {
      family: "Anton",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#00d2d3" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-38",
    name: "Effect 38",
    description: "Local text effect number 38",
    font: {
      family: "Bebas Neue",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#feca57" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-39",
    name: "Effect 39",
    description: "Local text effect number 39",
    font: {
      family: "Dancing Script",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#48dbfb" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-40",
    name: "Effect 40",
    description: "Local text effect number 40",
    font: {
      family: "Pacifico",
      weight: 400,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff9f43" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-41",
    name: "Effect 41",
    description: "Local text effect number 41",
    font: {
      family: "Nunito",
      weight: 500,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#10ac84" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-42",
    name: "Effect 42",
    description: "Local text effect number 42",
    font: {
      family: "Inter Variable",
      weight: 700,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ffffff" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-43",
    name: "Effect 43",
    description: "Local text effect number 43",
    font: {
      family: "Poppins",
      weight: 800,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff4757" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
  {
    id: "local-effect-44",
    name: "Effect 44",
    description: "Local text effect number 44",
    font: {
      family: "Roboto Variable",
      weight: 900,
      style: "normal",
      letterSpacing: 0,
      lineHeight: 1.2,
    },
    fills: [{ color: "#ff6b81" }],
    shadows: [{ color: "#000000", blur: 4, offsetX: 1, offsetY: 1 }],
  },
];
