import type { StickerItem } from "./api/stickersApi";

export const LOCAL_STICKERS: StickerItem[] = [
  {
    id: "sticker1",
    name: "Sticker 1",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker1.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker1.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker1.webm",
    tags: ["emoji"],
  },
  {
    id: "sticker2",
    name: "Sticker 2",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker2.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker2.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker2.webm",
    tags: ["text"],
  },
  {
    id: "sticker3",
    name: "Sticker 3",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker3.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker3.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker3.webm",
    tags: ["gaming"],
  },
  {
    id: "sticker4",
    name: "Sticker 4",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker4.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker4.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker4.webm",
    tags: ["sports"],
  },
  {
    id: "sticker5",
    name: "Sticker 5",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker5.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker5.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker5.webm",
    tags: ["animals"],
  },
  {
    id: "sticker6",
    name: "Sticker 6",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker6.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker6.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker6.webm",
    tags: ["love"],
  },
  {
    id: "sticker7",
    name: "Sticker 7",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker7.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker7.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker7.webm",
    tags: ["mood"],
  },
  {
    id: "sticker8",
    name: "Sticker 8",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker8.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker8.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker8.webm",
    tags: ["food"],
  },
  {
    id: "sticker9",
    name: "Sticker 9",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker9.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker9.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker9.webm",
    tags: ["travel"],
  },
  {
    id: "sticker10",
    name: "Sticker 10",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker10.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker10.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker10.webm",
    tags: ["birthday"],
  },
  {
    id: "sticker11",
    name: "Sticker 11",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker11.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker11.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker11.webm",
    tags: ["frames"],
  },
  {
    id: "sticker12",
    name: "Sticker 12",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker12.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker12.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker12.webm",
    tags: ["shapes"],
  },
  {
    id: "sticker13",
    name: "Sticker 13",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker13.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker13.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker13.webm",
    tags: ["fashion"],
  },
  {
    id: "sticker14",
    name: "Sticker 14",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker14.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker14.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker14.webm",
    tags: ["retro"],
  },
  {
    id: "sticker15",
    name: "Sticker 15",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker15.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker15.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker15.webm",
    tags: ["illustration"],
  },
  {
    id: "sticker16",
    name: "Sticker 16",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker16.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker16.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker16.webm",
    tags: ["emoji"],
  },
  {
    id: "sticker17",
    name: "Sticker 17",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker17.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker17.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker17.webm",
    tags: ["text"],
  },
  {
    id: "sticker18",
    name: "Sticker 18",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker18.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker18.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker18.webm",
    tags: ["gaming"],
  },
  {
    id: "sticker19",
    name: "Sticker 19",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker19.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker19.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker19.webm",
    tags: ["sports"],
  },
  {
    id: "sticker20",
    name: "Sticker 20",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker20.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker20.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker20.webm",
    tags: ["animals"],
  },
  {
    id: "sticker21",
    name: "Sticker 21",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker21.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker21.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker21.webm",
    tags: ["love"],
  },
  {
    id: "sticker22",
    name: "Sticker 22",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker22.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker22.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker22.webm",
    tags: ["mood"],
  },
  {
    id: "sticker23",
    name: "Sticker 23",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker23.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker23.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker23.webm",
    tags: ["food"],
  },
  {
    id: "sticker24",
    name: "Sticker 24",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker24.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker24.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker24.webm",
    tags: ["travel"],
  },
  {
    id: "sticker25",
    name: "Sticker 25",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker25.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker25.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker25.webm",
    tags: ["birthday"],
  },
  {
    id: "sticker26",
    name: "Sticker 26",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker26.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker26.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker26.webm",
    tags: ["frames"],
  },
  {
    id: "sticker27",
    name: "Sticker 27",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker27.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker27.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker27.webm",
    tags: ["shapes"],
  },
  {
    id: "sticker28",
    name: "Sticker 28",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker28.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker28.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker28.webm",
    tags: ["fashion"],
  },
  {
    id: "sticker29",
    name: "Sticker 29",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker29.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker29.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker29.webm",
    tags: ["retro"],
  },
  {
    id: "sticker30",
    name: "Sticker 30",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker30.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker30.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker30.webm",
    tags: ["illustration"],
  },
  {
    id: "sticker31",
    name: "Sticker 31",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker31.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker31.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker31.webm",
    tags: ["emoji"],
  },
  {
    id: "sticker32",
    name: "Sticker 32",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker32.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker32.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker32.webm",
    tags: ["text"],
  },
  {
    id: "sticker33",
    name: "Sticker 33",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker33.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker33.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker33.webm",
    tags: ["gaming"],
  },
  {
    id: "sticker34",
    name: "Sticker 34",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker34.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker34.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker34.webm",
    tags: ["sports"],
  },
  {
    id: "sticker35",
    name: "Sticker 35",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker35.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker35.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker35.webm",
    tags: ["animals"],
  },
  {
    id: "sticker36",
    name: "Sticker 36",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker36.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker36.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker36.webm",
    tags: ["love"],
  },
  {
    id: "sticker37",
    name: "Sticker 37",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker37.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker37.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker37.webm",
    tags: ["mood"],
  },
  {
    id: "sticker38",
    name: "Sticker 38",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker38.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker38.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker38.webm",
    tags: ["food"],
  },
  {
    id: "sticker39",
    name: "Sticker 39",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker39.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker39.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker39.webm",
    tags: ["travel"],
  },
  {
    id: "sticker40",
    name: "Sticker 40",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker40.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker40.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker40.webm",
    tags: ["birthday"],
  },
  {
    id: "sticker41",
    name: "Sticker 41",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker41.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker41.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker41.webm",
    tags: ["frames"],
  },
  {
    id: "sticker42",
    name: "Sticker 42",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker42.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker42.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker42.webm",
    tags: ["shapes"],
  },
  {
    id: "sticker43",
    name: "Sticker 43",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker43.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker43.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker43.webm",
    tags: ["fashion"],
  },
  {
    id: "sticker44",
    name: "Sticker 44",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker44.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker44.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker44.webm",
    tags: ["retro"],
  },
  {
    id: "sticker45",
    name: "Sticker 45",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker45.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker45.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker45.webm",
    tags: ["illustration"],
  },
  {
    id: "sticker46",
    name: "Sticker 46",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker46.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker46.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker46.webm",
    tags: ["emoji"],
  },
  {
    id: "sticker47",
    name: "Sticker 47",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker47.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker47.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker47.webm",
    tags: ["text"],
  },
  {
    id: "sticker48",
    name: "Sticker 48",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker48.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker48.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker48.webm",
    tags: ["gaming"],
  },
  {
    id: "sticker49",
    name: "Sticker 49",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker49.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker49.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker49.webm",
    tags: ["sports"],
  },
  {
    id: "sticker50",
    name: "Sticker 50",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker50.png",
    lottieUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker50.json",
    preview: "https://raw.githubusercontent.com/testsharm/Clypra/main/public/assets/stickers/sticker50.webm",
    tags: ["animals"],
  }
];
