import type { StickerItem } from "./api/stickersApi";

export const LOCAL_STICKERS: StickerItem[] = [
  {
    id: "sticker1",
    name: "Grinning Face",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker1.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker2",
    name: "Smiling Eyes",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker2.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker3",
    name: "Tears of Joy",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker3.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker4",
    name: "Heart Eyes",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker4.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker5",
    name: "Fire",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker5.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker6",
    name: "Thumbs Up",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker6.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker7",
    name: "Clapping Hands",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker7.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker8",
    name: "Party Popper",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker8.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker9",
    name: "Star Eyes",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker9.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker10",
    name: "Cool Face",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker10.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker11",
    name: "OMG",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker11.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker12",
    name: "LOL",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker12.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker13",
    name: "WOW",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker13.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker14",
    name: "YES",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker14.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker15",
    name: "NO",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker15.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker16",
    name: "LOVE",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker16.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker17",
    name: "HEY",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker17.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker18",
    name: "OK",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker18.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker19",
    name: "GO",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker19.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker20",
    name: "STOP",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker20.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker21",
    name: "Game Over",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker21.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker22",
    name: "Level Up",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker22.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker23",
    name: "Victory",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker23.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker24",
    name: "Epic Win",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker24.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker25",
    name: "Player One",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker25.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker26",
    name: "Respawn",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker26.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker27",
    name: "Boss Fight",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker27.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker28",
    name: "Combo",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker28.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker29",
    name: "Quest",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker29.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker30",
    name: "Glitch",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker30.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker31",
    name: "Goal",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker31.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker32",
    name: "Home Run",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker32.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker33",
    name: "Slam Dunk",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker33.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker34",
    name: "Touchdown",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker34.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker35",
    name: "Champion",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker35.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker36",
    name: "Sprint",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker36.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker37",
    name: "Kick Off",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker37.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker38",
    name: "Home Plate",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker38.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker39",
    name: "Buzzer Beater",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker39.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker40",
    name: "Golden Medal",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker40.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker41",
    name: "Cute Cat",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker41.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker42",
    name: "Happy Dog",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker42.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker43",
    name: "Panda",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker43.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker44",
    name: "Bunny",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker44.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker45",
    name: "Fox",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker45.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker46",
    name: "Owl",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker46.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker47",
    name: "Penguin",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker47.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker48",
    name: "Koala",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker48.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker49",
    name: "Frog",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker49.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker50",
    name: "Tiger",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker50.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker51",
    name: "Heart",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker51.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker52",
    name: "Kiss",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker52.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker53",
    name: "Love Letter",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker53.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker54",
    name: "Cupid",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker54.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker55",
    name: "Hug",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker55.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker56",
    name: "Sparkle Heart",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker56.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker57",
    name: "Valentine",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker57.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker58",
    name: "Sweetheart",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker58.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker59",
    name: "Adore",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker59.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker60",
    name: "Cherish",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker60.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker61",
    name: "Mood",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker61.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker62",
    name: "Vibes",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker62.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker63",
    name: "Chill",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker63.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker64",
    name: "Lit",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker64.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker65",
    name: "Sad",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker65.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker66",
    name: "Angry",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker66.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker67",
    name: "Happy",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker67.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker68",
    name: "Excited",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker68.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker69",
    name: "Tired",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker69.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker70",
    name: "Bored",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker70.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker71",
    name: "Pizza",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker71.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker72",
    name: "Burger",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker72.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker73",
    name: "Ice Cream",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker73.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker74",
    name: "Taco",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker74.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker75",
    name: "Sushi",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker75.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker76",
    name: "Donut",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker76.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker77",
    name: "Fries",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker77.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker78",
    name: "Pancakes",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker78.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker79",
    name: "Ramen",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker79.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker80",
    name: "Cookie",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker80.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker81",
    name: "Passport",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker81.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker82",
    name: "Airplane",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker82.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker83",
    name: "Beach",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker83.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker84",
    name: "Mountain",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker84.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker85",
    name: "City",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker85.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker86",
    name: "Camping",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker86.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker87",
    name: "Adventure",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker87.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker88",
    name: "Globe",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker88.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker89",
    name: "Map",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker89.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker90",
    name: "Suitcase",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker90.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker91",
    name: "Happy Birthday",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker91.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker92",
    name: "Cake",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker92.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker93",
    name: "Balloons",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker93.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker94",
    name: "Party Popper",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker94.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker95",
    name: "Gift",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker95.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker96",
    name: "Candles",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker96.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker97",
    name: "Confetti",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker97.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker98",
    name: "Cupcake",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker98.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker99",
    name: "Party Hat",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker99.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker100",
    name: "Celebrate",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker100.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
];

