import type { StickerItem } from "./api/stickersApi";

export const LOCAL_STICKERS: StickerItem[] = [
  {
    id: "sticker1",
    name: "Grinning Face",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker1.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker2",
    name: "Smiling Eyes",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker2.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker3",
    name: "Tears of Joy",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker3.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker4",
    name: "Heart Eyes",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker4.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker5",
    name: "Fire",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker5.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker6",
    name: "Thumbs Up",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker6.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker7",
    name: "Clapping Hands",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker7.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker8",
    name: "Party Popper",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker8.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker9",
    name: "Star Eyes",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker9.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker10",
    name: "Cool Face",
    category: "emoji",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker10.svg",
    lottieUrl: "",
    preview: "",
    tags: ["emoji"],
  },
  {
    id: "sticker11",
    name: "OMG",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker11.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker12",
    name: "LOL",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker12.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker13",
    name: "WOW",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker13.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker14",
    name: "YES",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker14.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker15",
    name: "NO",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker15.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker16",
    name: "LOVE",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker16.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker17",
    name: "HEY",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker17.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker18",
    name: "OK",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker18.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker19",
    name: "GO",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker19.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker20",
    name: "STOP",
    category: "text",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker20.svg",
    lottieUrl: "",
    preview: "",
    tags: ["text"],
  },
  {
    id: "sticker21",
    name: "Game Over",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker21.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker22",
    name: "Level Up",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker22.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker23",
    name: "Victory",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker23.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker24",
    name: "Epic Win",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker24.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker25",
    name: "Player One",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker25.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker26",
    name: "Respawn",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker26.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker27",
    name: "Boss Fight",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker27.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker28",
    name: "Combo",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker28.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker29",
    name: "Quest",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker29.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker30",
    name: "Glitch",
    category: "gaming",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker30.svg",
    lottieUrl: "",
    preview: "",
    tags: ["gaming"],
  },
  {
    id: "sticker31",
    name: "Goal",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker31.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker32",
    name: "Home Run",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker32.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker33",
    name: "Slam Dunk",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker33.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker34",
    name: "Touchdown",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker34.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker35",
    name: "Champion",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker35.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker36",
    name: "Sprint",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker36.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker37",
    name: "Kick Off",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker37.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker38",
    name: "Home Plate",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker38.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker39",
    name: "Buzzer Beater",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker39.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker40",
    name: "Golden Medal",
    category: "sports",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker40.svg",
    lottieUrl: "",
    preview: "",
    tags: ["sports"],
  },
  {
    id: "sticker41",
    name: "Cute Cat",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker41.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker42",
    name: "Happy Dog",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker42.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker43",
    name: "Panda",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker43.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker44",
    name: "Bunny",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker44.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker45",
    name: "Fox",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker45.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker46",
    name: "Owl",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker46.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker47",
    name: "Penguin",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker47.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker48",
    name: "Koala",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker48.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker49",
    name: "Frog",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker49.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker50",
    name: "Tiger",
    category: "animals",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker50.svg",
    lottieUrl: "",
    preview: "",
    tags: ["animals"],
  },
  {
    id: "sticker51",
    name: "Heart",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker51.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker52",
    name: "Kiss",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker52.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker53",
    name: "Love Letter",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker53.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker54",
    name: "Cupid",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker54.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker55",
    name: "Hug",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker55.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker56",
    name: "Sparkle Heart",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker56.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker57",
    name: "Valentine",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker57.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker58",
    name: "Sweetheart",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker58.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker59",
    name: "Adore",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker59.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker60",
    name: "Cherish",
    category: "love",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker60.svg",
    lottieUrl: "",
    preview: "",
    tags: ["love"],
  },
  {
    id: "sticker61",
    name: "Mood",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker61.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker62",
    name: "Vibes",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker62.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker63",
    name: "Chill",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker63.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker64",
    name: "Lit",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker64.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker65",
    name: "Sad",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker65.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker66",
    name: "Angry",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker66.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker67",
    name: "Happy",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker67.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker68",
    name: "Excited",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker68.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker69",
    name: "Tired",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker69.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker70",
    name: "Bored",
    category: "mood",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker70.svg",
    lottieUrl: "",
    preview: "",
    tags: ["mood"],
  },
  {
    id: "sticker71",
    name: "Pizza",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker71.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker72",
    name: "Burger",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker72.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker73",
    name: "Ice Cream",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker73.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker74",
    name: "Taco",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker74.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker75",
    name: "Sushi",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker75.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker76",
    name: "Donut",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker76.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker77",
    name: "Fries",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker77.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker78",
    name: "Pancakes",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker78.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker79",
    name: "Ramen",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker79.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker80",
    name: "Cookie",
    category: "food",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker80.svg",
    lottieUrl: "",
    preview: "",
    tags: ["food"],
  },
  {
    id: "sticker81",
    name: "Passport",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker81.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker82",
    name: "Airplane",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker82.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker83",
    name: "Beach",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker83.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker84",
    name: "Mountain",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker84.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker85",
    name: "City",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker85.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker86",
    name: "Camping",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker86.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker87",
    name: "Adventure",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker87.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker88",
    name: "Globe",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker88.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker89",
    name: "Map",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker89.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker90",
    name: "Suitcase",
    category: "travel",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker90.svg",
    lottieUrl: "",
    preview: "",
    tags: ["travel"],
  },
  {
    id: "sticker91",
    name: "Happy Birthday",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker91.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker92",
    name: "Cake",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker92.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker93",
    name: "Balloons",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker93.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker94",
    name: "Party Popper",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker94.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker95",
    name: "Gift",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker95.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker96",
    name: "Candles",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker96.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker97",
    name: "Confetti",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker97.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker98",
    name: "Cupcake",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker98.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker99",
    name: "Party Hat",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker99.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker100",
    name: "Celebrate",
    category: "birthday",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker100.svg",
    lottieUrl: "",
    preview: "",
    tags: ["birthday"],
  },
  {
    id: "sticker101",
    name: "Circle",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker101.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker102",
    name: "Square",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker102.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker103",
    name: "Star",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker103.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker104",
    name: "Heart Frame",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker104.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker105",
    name: "Diamond",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker105.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker106",
    name: "Hexagon",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker106.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker107",
    name: "Rounded",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker107.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker108",
    name: "Banner",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker108.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker109",
    name: "Shield",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker109.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker110",
    name: "Badge",
    category: "frames",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker110.svg",
    lottieUrl: "",
    preview: "",
    tags: ["frames"],
  },
  {
    id: "sticker111",
    name: "Arrow",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker111.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker112",
    name: "Sparkle",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker112.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker113",
    name: "Burst",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker113.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker114",
    name: "Banner",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker114.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker115",
    name: "Cloud",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker115.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker116",
    name: "Lightning",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker116.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker117",
    name: "Moon",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker117.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker118",
    name: "Sun",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker118.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker119",
    name: "Rainbow",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker119.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker120",
    name: "Flower",
    category: "shapes",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker120.svg",
    lottieUrl: "",
    preview: "",
    tags: ["shapes"],
  },
  {
    id: "sticker121",
    name: "Cool Shades",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker121.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker122",
    name: "Lipstick",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker122.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker123",
    name: "High Heels",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker123.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker124",
    name: "Hat",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker124.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker125",
    name: "Necklace",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker125.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker126",
    name: "Watch",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker126.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker127",
    name: "Bag",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker127.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker128",
    name: "Sneaker",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker128.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker129",
    name: "Dress",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker129.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker130",
    name: "Bow Tie",
    category: "fashion",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker130.svg",
    lottieUrl: "",
    preview: "",
    tags: ["fashion"],
  },
  {
    id: "sticker131",
    name: "Retro TV",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker131.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker132",
    name: "Cassette",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker132.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker133",
    name: "Pixel Heart",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker133.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker134",
    name: "8-bit",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker134.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker135",
    name: "Arcade",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker135.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker136",
    name: "Boombox",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker136.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker137",
    name: "Floppy Disk",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker137.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker138",
    name: "Game Boy",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker138.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker139",
    name: "Vinyl",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker139.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker140",
    name: "Walkman",
    category: "retro",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker140.svg",
    lottieUrl: "",
    preview: "",
    tags: ["retro"],
  },
  {
    id: "sticker141",
    name: "Doodle",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker141.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker142",
    name: "Sketch",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker142.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker143",
    name: "Watercolor",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker143.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker144",
    name: "Ink",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker144.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker145",
    name: "Pencil",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker145.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker146",
    name: "Brush",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker146.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker147",
    name: "Palette",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker147.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker148",
    name: "Canvas",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker148.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker149",
    name: "Comic",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker149.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
  {
    id: "sticker150",
    name: "Cartoon",
    category: "illustration",
    thumbnailUrl: "https://raw.githubusercontent.com/testsharm/Clypra/main/github-assets/stickers/sticker150.svg",
    lottieUrl: "",
    preview: "",
    tags: ["illustration"],
  },
];

